package in.craves.adminexplorer;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
public class ExplorerQueryTest {
 public static final Instant NOW=Instant.parse("2026-09-15T00:00:00Z");
 public static ExplorerQuery.Request request(String from,String to,String status,String search,String facet,Integer size,String sort,String mode,String boundary,String cursor,String reason){return new ExplorerQuery.Request(from,to,status,search,facet,size,sort,mode,boundary,cursor,reason);}
 public static ExplorerQuery.Request normal(){return request("","","","","",25,"newest","records",null,null,"Investigate onboarding progress");}
 @Test void allTimeIsNotLimitedToRecentRows(){var q=ExplorerQuery.parse(normal(),ExplorerDomain.DATASET,NOW);assertNull(q.from());assertNull(q.start());assertEquals(NOW,q.end());assertEquals(25,q.size());}
 @Test void datesUseInclusiveIstCalendarDays(){var q=ExplorerQuery.parse(request("2026-09-10","2026-09-10","","","",25,"newest","records",null,null,"Review this calendar day"),ExplorerDomain.DATASET,NOW);assertEquals(Instant.parse("2026-09-09T18:30:00Z"),q.start());assertEquals(Instant.parse("2026-09-10T18:30:00Z"),q.end());}
 @Test void invalidCalendarAndReversedDatesFail(){for(String d:List.of("2026-02-29","2026-02-31","2026-13-01","01-01-2026"))assertThrows(IllegalArgumentException.class,()->ExplorerQuery.date(d));assertThrows(IllegalArgumentException.class,()->ExplorerQuery.parse(request("2026-09-12","2026-09-10","","","",25,"newest","summary",null,null,null),ExplorerDomain.DATASET,NOW));}
 @Test void paginationAndSortAreAllowlisted(){for(int size:List.of(-1,0,20,26,101,Integer.MAX_VALUE))assertThrows(IllegalArgumentException.class,()->ExplorerQuery.parse(request("","","","","",size,"newest","summary",null,null,null),ExplorerDomain.DATASET,NOW));assertThrows(IllegalArgumentException.class,()->ExplorerQuery.parse(request("","","","","",25,"id; DROP","summary",null,null,null),ExplorerDomain.DATASET,NOW));}
 @Test void cursorIsBoundToFiltersAndCutoff(){var q=ExplorerQuery.parse(normal(),ExplorerDomain.DATASET,NOW);String token=q.next(NOW.minusSeconds(60),UUID.randomUUID());var same=ExplorerQuery.parse(request("","","","","",25,"newest","records",NOW.toString(),token,"Review next page of users"),ExplorerDomain.DATASET,NOW);assertNotNull(same.afterId());assertThrows(IllegalArgumentException.class,()->ExplorerQuery.parse(request("","","ACTIVE","","",25,"newest","records",NOW.toString(),token,"Review next page of users"),ExplorerDomain.DATASET,NOW));assertThrows(IllegalArgumentException.class,()->ExplorerQuery.parse(request("","","","","",25,"newest","records",NOW.minusSeconds(1).toString(),token,"Review next page of users"),ExplorerDomain.DATASET,NOW));}
 @Test void recordsRequireReasonAndFutureBoundaryFails(){assertThrows(IllegalArgumentException.class,()->ExplorerQuery.parse(request("","","","","",25,"newest","records",null,null,"short"),ExplorerDomain.DATASET,NOW));assertThrows(IllegalArgumentException.class,()->ExplorerQuery.parse(request("","","","","",25,"newest","summary",NOW.plusSeconds(10).toString(),null,null),ExplorerDomain.DATASET,NOW));}
 @Test void wildcardTextIsLiteralAndControlCharactersFail(){assertEquals("%a!_!%!!%",ExplorerQuery.like("a_%!"));assertThrows(IllegalArgumentException.class,()->ExplorerQuery.text("text\nvalue",160));assertThrows(IllegalArgumentException.class,()->ExplorerQuery.text("x".repeat(161),160));}
 @Test void unsafeCountAndContactsAreGuarded(){assertThrows(IllegalStateException.class,()->ExplorerEngine.safeCount(9007199254740992L));assertEquals("•••• 1234",ExplorerEngine.maskPhone("+919999991234"));assertEquals("a•••@•••",ExplorerEngine.maskEmail("admin@example.test"));assertNull(ExplorerEngine.maskPhone(null));}
}
