package in.craves.order.finance;
import in.craves.order.referrals.*;
import in.craves.order.referrals.transport.ReferralSourceClient;
import in.craves.order.web.ApiDtos.CheckoutRequest;
import java.math.BigDecimal;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.springframework.core.env.MapPropertySource;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
@org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable(named="LEDGER_TEST_JDBC_URL",matches=".+")
class ReferralBenefitsOwnerDatabaseTest extends ReferralCheckoutIntegrationDatabaseTest {
 @Override void registerAdditionalOwners(){super.registerAdditionalOwners();context.getEnvironment().getPropertySources().addFirst(new MapPropertySource("benefits-test",Map.of("CRAVES_REFERRAL_CHECKOUT_BENEFITS_ENABLED","true")));context.registerBean(ReferralCheckoutBenefits.class);context.registerBean(ReferralCheckoutBenefitsAspect.class);}
 ReferralCheckoutBenefits service(){return context.getBean(ReferralCheckoutBenefits.class);}
 void replies()throws Exception{doAnswer(call->{var envelope=json.readTree((byte[])call.getArgument(1));var p=envelope.path("payload");boolean reserve=envelope.path("operationType").asText().equals("checkout.reserve");var value=json.createObjectNode().put("checkoutId",p.path("checkoutId").asText()).put("buyerUserId",p.path("buyerUserId").asText()).put("grossPaise","43347").put("walletPaise","1000").put("discountPaise","0").put("gatewayPaise","42347").put("status",reserve?"RESERVED":"CONSUMED");return new ReferralSourceClient.Reply(200,json.writeValueAsBytes(value));}).when(referral).send(eq(ReferralSourceClient.Endpoint.OPERATIONS),any());}
 @Test void optedInCheckoutPersistsIntentWithUnchangedGrossAndTax()throws Exception{replies();var value=orders.checkout(actor,new CheckoutRequest(address,"test",json.createObjectNode().put("walletPaise","1000").put("inviteeDiscount",false)));assertTrue(value.referralBenefitsRequested());assertTrue(orders.getCheckout(actor,value.id()).referralBenefitsRequested());assertEquals(new BigDecimal("433.47"),value.grandTotal());assertEquals(1,count("referral_checkout_benefit"));assertTrue(service().runOne());assertEquals("RESERVED",service().read(actor,value.id()).path("state").asText());assertEquals("42347",service().read(actor,value.id()).path("funding").path("gatewayPaise").asText());}
 @Test void consumeWaitsForCoreReceiptAndDuplicateCallbackHasNoSecondEffect()throws Exception{replies();var value=orders.checkout(actor,new CheckoutRequest(address,"test",json.createObjectNode().put("walletPaise","1000").put("inviteeDiscount",false)));service().runOne();assertFalse(service().requestConsumption(value.id()));assertTrue(service().runOne());assertTrue(service().requestConsumption(value.id()));assertFalse(service().runOne());assertEquals("CONSUMED",service().read(actor,value.id()).path("state").asText());}
 @Test void discountedCheckoutBelowMinimumRollsBackCheckoutCartAndSources(){assertThrows(Exception.class,()->orders.checkout(actor,new CheckoutRequest(address,"test",json.createObjectNode().put("walletPaise","0").put("inviteeDiscount",true))));assertEquals(0,count("checkout"));assertEquals(1,count("cart_item"));assertEquals(0,count("referral_source_outbox"));}
 @Test void uncertainReservationKeepsOriginalOperationForRetry()throws Exception{replies();var value=orders.checkout(actor,new CheckoutRequest(address,"test",json.createObjectNode().put("walletPaise","1000").put("inviteeDiscount",false)));doThrow(new java.io.IOException("test timeout")).when(referral).send(eq(ReferralSourceClient.Endpoint.OPERATIONS),any());assertTrue(service().runOne());String original=jdbc.queryForObject("SELECT reserve_envelope::text FROM order_schema.referral_checkout_benefit",String.class);replies();jdbc.execute("UPDATE order_schema.referral_checkout_benefit SET next_attempt_at=now()");assertTrue(service().runOne());assertEquals(original,jdbc.queryForObject("SELECT reserve_envelope::text FROM order_schema.referral_checkout_benefit",String.class));assertEquals("RESERVED",service().read(actor,value.id()).path("state").asText());}
 @Test void anotherCustomerCannotReadTheBenefitPlan(){var value=checkout();var stranger=new in.craves.order.security.CravesPrincipal(java.util.UUID.randomUUID(),"",java.util.Set.of("CUSTOMER"));assertThrows(Exception.class,()->service().read(stranger,value.id()));}
 @Test void confirmedUnpaidCancellationReleasesBothAndRecordsOrderHistory()throws Exception{replies();var value=orders.checkout(actor,new CheckoutRequest(address,"test",json.createObjectNode().put("walletPaise","1000").put("inviteeDiscount",false)));service().runOne();assertFalse(service().requestRelease(value.id()));doAnswer(call->{var p=json.readTree((byte[])call.getArgument(1)).path("payload");return new ReferralSourceClient.Reply(200,json.writeValueAsBytes(json.createObjectNode().put("checkoutId",p.path("checkoutId").asText()).put("walletPaise","1000").put("discountPaise","0").put("status","RELEASED")));}).when(referral).send(eq(ReferralSourceClient.Endpoint.OPERATIONS),any());assertTrue(service().runOne());assertTrue(service().requestRelease(value.id()));assertEquals("CANCELLED",jdbc.queryForObject("SELECT status FROM order_schema.checkout",String.class));assertEquals("CANCELLED",jdbc.queryForObject("SELECT status FROM order_schema.customer_order",String.class));assertEquals(1,jdbc.queryForObject("SELECT count(*) FROM order_schema.order_status_history WHERE new_status='CANCELLED'",Integer.class));}

}
