package in.craves.integration.referrals.payout;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import in.craves.integration.referrals.ReferralDatabase;
import in.craves.integration.referrals.transport.ReferralOutbox;
import in.craves.integration.ledger.LedgerPostingService;
import in.craves.integration.payout.RazorpayXPayoutClient;
import in.craves.integration.security.CravesPrincipal;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
@EnabledIfEnvironmentVariable(named="LEDGER_TEST_JDBC_URL",matches=".+")
class ReferralPayoutDatabaseTest {
 ReferralDatabase r;ObjectMapper json=new ObjectMapper().findAndRegisterModules();RazorpayXPayoutClient provider;ReferralFinanceReviewService reviews;ReferralPayoutWorker worker;
 CravesPrincipal maker,checker;UUID user,assessment,attempt,reservation;
 @BeforeEach void setup(){r=new ReferralDatabase();provider=mock(RazorpayXPayoutClient.class);when(provider.ready()).thenReturn(true);var out=new ReferralOutbox(r.db,json,r.tx);var ledger=new LedgerPostingService(r.db,json,true);reviews=new ReferralFinanceReviewService(r.db,json,out,provider,r.manager);worker=new ReferralPayoutWorker(r.db,json,provider,out,ledger,r.manager,true);maker=actor();checker=actor();user=UUID.randomUUID();assessment=UUID.randomUUID();attempt=UUID.randomUUID();reservation=UUID.randomUUID();}
 CravesPrincipal actor(){return new CravesPrincipal(UUID.randomUUID(),null,Set.of("PAYMENTS_ADMIN"));}
 ObjectNode recipient(){var now=Instant.now();var day=now.atZone(ZoneId.of("Asia/Kolkata"));int year=day.getMonthValue()>=4?day.getYear():day.getYear()-1;return json.createObjectNode().put("assessmentId",assessment.toString()).put("userId",user.toString()).put("financialYear",year+"-"+(year+1)).put("kycVerified",true).put("kycExpiresAt",now.plusSeconds(86400).toString()).put("destinationRef","TEST_ONLY_DESTINATION").put("taxAssessmentRef","TEST_ONLY_TAX").put("taxHandling","REVIEWED_AT_CASHOUT").put("cashoutAllowed",true).put("annualLimitPaise","1000000").put("assessedAt",now.toString());}
 Map<String,Object> draft(){return reviews.draft(maker,new ReferralFinanceReviewService.Draft("RECIPIENT",recipient(),"fa_TestOnly","cont_TestOnly","TEST_ONLY_BANK_OWNERSHIP","Synthetic disposable test"));}
 void approved(){var d=draft();reviews.approve(checker,(UUID)d.get("id"),new ReferralFinanceReviewService.Approval(d.get("contentHash").toString(),"Synthetic independent review"));}
 void instruction(){var p=json.createObjectNode().put("attemptId",attempt.toString()).put("reservationId",reservation.toString()).put("beneficiaryUserId",user.toString()).put("assessmentId",assessment.toString()).put("destinationRef","TEST_ONLY_DESTINATION").put("grossPaise","11000").put("netPaise","10000").put("withholdingPaise","1000").put("currency","INR");r.db.update("INSERT INTO payment_schema.referral_payout_instruction(attempt_id,reservation_id,user_id,payload,source_event_id) VALUES (?,?,?,?::jsonb,?)",attempt,reservation,user,p.toString(),UUID.randomUUID());}
 String state(){return r.db.queryForObject("SELECT state FROM payment_schema.referral_payout_execution WHERE attempt_id=?",String.class,attempt);}
 void due(){r.db.update("UPDATE payment_schema.referral_payout_execution SET next_attempt_at=now()-interval '1 second' WHERE attempt_id=?",attempt);}
 @Test void requesterCannotApproveAndChangingReviewedHashFails(){var d=draft();assertThrows(Exception.class,()->reviews.approve(maker,(UUID)d.get("id"),new ReferralFinanceReviewService.Approval(d.get("contentHash").toString(),"test")));assertThrows(Exception.class,()->reviews.approve(checker,(UUID)d.get("id"),new ReferralFinanceReviewService.Approval("bad","test")));assertEquals(0,r.count("referral_source_outbox"));}
 @Test void approvalPublishesExactlyOneOriginalAssessmentAndLocksEvidence(){var d=draft();var a=new ReferralFinanceReviewService.Approval(d.get("contentHash").toString(),"test");reviews.approve(checker,(UUID)d.get("id"),a);reviews.approve(checker,(UUID)d.get("id"),a);assertEquals(1,r.count("referral_source_outbox"));assertThrows(Exception.class,()->r.db.execute("UPDATE payment_schema.referral_finance_review SET payload='{}'"));}
 @Test void unreviewedRecipientNeverExecutes(){instruction();assertFalse(worker.runOne());verify(provider,never()).submitReferral(any());assertEquals(0,r.count("referral_payout_execution"));}
 @Test void timeoutKeepsOriginalAttemptReservedAndNeverResubmits(){approved();instruction();when(provider.submitReferral(any())).thenThrow(new IllegalStateException("test timeout"));assertTrue(worker.runOne());assertEquals("UNKNOWN",state());due();assertFalse(worker.runOne());verify(provider,times(1)).submitReferral(any());assertEquals(0,r.count("ledger_transaction"));assertEquals(1,r.db.queryForObject("SELECT count(*) FROM payment_schema.referral_payout_evidence WHERE outcome='UNKNOWN'",Integer.class));}
 @Test void paidReceiptPostsOnlyNetClearingOnceAndPublishesOriginalAmounts(){approved();instruction();when(provider.submitReferral(any())).thenReturn(new RazorpayXPayoutClient.Receipt("pout_TestOnly","processed","TEST_UTR"));assertTrue(worker.runOne());assertEquals("PAID",state());assertFalse(worker.runOne());assertEquals(1,r.count("ledger_transaction"));assertEquals(0,r.db.queryForObject("SELECT count(*) FROM payment_schema.ledger_line WHERE chef_identity_id IS NOT NULL OR account_code='CHEF_PAYABLE'",Integer.class));var payload=r.db.queryForObject("SELECT envelope::jsonb->'payload'->>'netPaise' FROM payment_schema.referral_source_outbox WHERE envelope::jsonb->>'eventType'='payout.outcome'",String.class);assertEquals("10000",payload);verify(provider,times(1)).submitReferral(any());assertThrows(Exception.class,()->r.db.execute("UPDATE payment_schema.referral_payout_execution SET state='READY'"));}
 @Test void failedSubmissionRequiresIndependentGetBeforeRelease(){approved();instruction();when(provider.submitReferral(any())).thenReturn(new RazorpayXPayoutClient.Receipt("pout_TestOnly","failed",null));assertTrue(worker.runOne());assertEquals("UNKNOWN",state());due();when(provider.fetch(any())).thenReturn(new RazorpayXPayoutClient.Receipt("pout_TestOnly","failed",null));assertTrue(worker.runOne());assertEquals("FAILED",state());assertEquals(0,r.count("ledger_transaction"));assertEquals(1,r.db.queryForObject("SELECT count(*) FROM payment_schema.referral_payout_evidence WHERE outcome='PROVEN_FAILED'",Integer.class));}
 @Test void processedWithoutUtrAndReversedRemainUnresolved(){approved();instruction();when(provider.submitReferral(any())).thenReturn(new RazorpayXPayoutClient.Receipt("pout_TestOnly","processed",null));worker.runOne();assertEquals("UNKNOWN",state());due();when(provider.fetch(any())).thenReturn(new RazorpayXPayoutClient.Receipt("pout_TestOnly","reversed",null));worker.runOne();assertEquals("UNKNOWN",state());assertEquals(0,r.count("ledger_transaction"));}
 @Test void staleWorkerCannotCommitAndReplacementDoesNotSubmit(){approved();instruction();worker.freezeOne();var work=worker.claim();assertNotNull(work);r.db.execute("UPDATE payment_schema.referral_payout_execution SET lease_until=now()-interval '1 second'");worker.finish(work,new RazorpayXPayoutClient.Receipt("pout_TestOnly","processed","UTR"));assertEquals(0,r.count("ledger_transaction"));assertFalse(worker.runOne());assertEquals("UNKNOWN",state());verify(provider,never()).submitReferral(any());}
 @Test void reconciliationVerifiesOriginalProviderIdentityAndPreservesAttempt(){approved();instruction();when(provider.submitReferral(any())).thenThrow(new IllegalStateException("timeout"));worker.runOne();when(provider.fetch(any())).thenReturn(new RazorpayXPayoutClient.Receipt("pout_TestOnly","processed","UTR"));worker.reconcile(checker,attempt,new ReferralPayoutWorker.Reconcile("pout_TestOnly","TEST_ONLY_PROVIDER_LOOKUP","test"));worker.runOne();assertEquals("PAID",state());verify(provider,times(1)).submitReferral(any());verify(provider,atLeast(1)).fetch(argThat(i->i.id().equals(attempt)&&i.fundAccountId().equals("fa_TestOnly")&&i.amount().equals("100.00")));}
 @Test void readerCannotCreateReview(){var reader=new CravesPrincipal(UUID.randomUUID(),null,Set.of("AUDIT_ADMIN"));assertThrows(Exception.class,()->reviews.draft(reader,new ReferralFinanceReviewService.Draft("RECIPIENT",recipient(),"fa_TestOnly","cont_TestOnly","TEST_ONLY_BANK","test")));}
 @Test void disabledExecutionDoesNotClaimInstructions(){approved();instruction();var out=new ReferralOutbox(r.db,json,r.tx);var disabled=new ReferralPayoutWorker(r.db,json,provider,out,new LedgerPostingService(r.db,json,true),r.manager,false);assertFalse(disabled.runOne());assertEquals(0,r.count("referral_payout_execution"));}
 @Test void simultaneousWorkersCreateOnlyOneProviderTransfer() throws Exception {approved();instruction();var entered=new CountDownLatch(1);var release=new CountDownLatch(1);when(provider.submitReferral(any())).thenAnswer(i->{entered.countDown();assertTrue(release.await(10,TimeUnit.SECONDS));return new RazorpayXPayoutClient.Receipt("pout_TestOnly","processed","UTR");});try(var pool=Executors.newFixedThreadPool(2)){var first=pool.submit(worker::runOne);assertTrue(entered.await(10,TimeUnit.SECONDS));assertFalse(pool.submit(worker::runOne).get(10,TimeUnit.SECONDS));release.countDown();assertTrue(first.get(10,TimeUnit.SECONDS));}verify(provider,times(1)).submitReferral(any());assertEquals("PAID",state());}
}
