import test from "node:test";
import assert from "node:assert/strict";
import {EMPTY_FILTERS,aggregateCsv,calendarDate,explorerHref,parseExplorerRequest,parseExplorerResult,presetDates,publicFilters} from "./admin-explorer.ts";
const id="00000000-0000-4000-8000-000000000001";
function report(){return {dataset:"users",correlationId:id,generatedAt:"2026-09-14T12:00:00Z",boundary:"2026-09-14T12:00:00Z",total:1,populationTotal:1,statuses:[{key:"ACTIVE",count:1}],trend:[{fromDate:"2026-09-10",toDate:"2026-09-10",count:1}],bucketUnit:"day",rows:[],nextCursor:null,pageSize:25,sort:"newest",mode:"summary"};}
function row(){return {id,identityId:id,label:"Synthetic user",status:"ACTIVE",createdAt:"2026-09-10T12:00:00Z",updatedAt:"2026-09-10T12:00:00Z",phone:"•••• 1111",email:"t•••@•••",city:null,roles:["CUSTOMER","CHEF"],orderSource:null,amount:null,currency:null,customerId:null,chefId:null,kitchenId:null,checkoutId:null};}
test("calendar filters reject rollover dates",()=>{assert.ok(calendarDate("2024-02-29"));for(const d of ["2026-02-29","2026-02-31","2026-13-01","bad"])assert.equal(calendarDate(d),false);});
test("records require a purpose while summaries contain no record reason",()=>{assert.equal(parseExplorerRequest({...EMPTY_FILTERS,mode:"records"},"users"),null);assert.ok(parseExplorerRequest({...EMPTY_FILTERS,mode:"records",reason:"Review customer onboarding"},"users"));assert.equal(parseExplorerRequest({...EMPTY_FILTERS,mode:"summary",reason:"not forwarded"},"users")?.reason,undefined);});
test("only declared filters and domain facets are accepted",()=>{assert.equal(parseExplorerRequest({...EMPTY_FILTERS,mode:"summary",sql:"DELETE"},"users"),null);assert.equal(parseExplorerRequest({...EMPTY_FILTERS,mode:"summary",facet:"DROP TABLE"},"users"),null);assert.equal(parseExplorerRequest({...EMPTY_FILTERS,mode:"summary",facet:"SCHEDULED"},"orders"),null);assert.ok(parseExplorerRequest({...EMPTY_FILTERS,mode:"summary",facet:"Hyderabad"},"chefs"));});
test("page sizes and cursor shape fail closed",()=>{for(const pageSize of [0,20,26,101])assert.equal(parseExplorerRequest({...EMPTY_FILTERS,pageSize,mode:"summary"},"users"),null);assert.equal(parseExplorerRequest({...EMPTY_FILTERS,mode:"summary",cursor:"x"},"users"),null);});
test("all-user count is independent of customer and chef role overlap",()=>{const r=parseExplorerResult({...report(),mode:"records",rows:[row()]},"users");assert.equal(r?.total,1);assert.equal(r?.rows[0].roles.length,2);});
test("aggregation, duplicates and precision are checked",()=>{assert.ok(parseExplorerResult(report(),"users"));assert.equal(parseExplorerResult({...report(),total:2},"users"),null);assert.equal(parseExplorerResult({...report(),populationTotal:Number.MAX_SAFE_INTEGER+1},"users"),null);assert.equal(parseExplorerResult({...report(),mode:"records",rows:[row(),row()]},"users"),null);assert.equal(parseExplorerResult({...report(),dataset:"orders"},"users"),null);});
test("unmasked upstream contacts are never forwarded",()=>{assert.equal(parseExplorerResult({...report(),mode:"records",rows:[{...row(),phone:"+919999991111"}]},"users"),null);assert.equal(parseExplorerResult({...report(),mode:"records",rows:[{...row(),email:"test@example.test"}]},"users"),null);});
test("summary mode cannot smuggle individual records",()=>{assert.equal(parseExplorerResult({...report(),rows:[row()]},"users"),null);});
test("links exclude sensitive filters and encode exact graph selections",()=>{const href=explorerHref("chefs",{...EMPTY_FILTERS,fromDate:"2026-09-10",toDate:"2026-09-11",status:"APPROVED",search:"test@example.test",facet:"Hyderabad"});assert.equal(href,"/admin/explorer/chefs?from=2026-09-10&to=2026-09-11&status=APPROVED");assert.doesNotMatch(href,/example|Hyderabad/);assert.equal(publicFilters({from:"2026-02-31",status:"DROP TABLE"}).status,"");});
test("preset periods use the IST date even when UTC is on the previous day",()=>{assert.deepEqual(presetDates(1,new Date("2026-09-14T20:00:00Z")),{fromDate:"2026-09-15",toDate:"2026-09-15"});assert.deepEqual(presetDates(0),{fromDate:"",toDate:""});});
test("aggregate export does not contain user details or role rows",()=>{const r=parseExplorerResult({...report(),mode:"records",rows:[row()]},"users");assert.ok(r);const csv=aggregateCsv(r);assert.match(csv,/status_before_status_filter/);assert.doesNotMatch(csv,/Synthetic|1111|CHEF|CUSTOMER/);});
