package in.craves.referral;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import in.craves.referral.infra.Json;
import java.util.*;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
class ReferralCheckoutBenefitsIT {
 ReferralTestRig r;ReferralTestRig.Member buyer;ReferralTestRig.Order order;
 @BeforeEach void setup(){r=new ReferralTestRig();buyer=r.member(r.member(null));order=r.order(r.member(null),buyer,80000,100000);r.fund("DISCOUNT",100000);r.db.tx(()->{r.db.journal("TEST_ONLY_CREDIT",buyer.id(),0,50000,0,"MARKETING_EXPENSE",null,null);return null;});}
 ObjectNode reserve(long wallet){return Json.MAPPER.createObjectNode().put("checkoutId",order.checkout().toString()).put("buyerUserId",buyer.id().toString()).put("grossPaise","100000").put("foodSubtotalPaise","80000").put("walletPaise",Long.toString(wallet)).put("inviteeDiscount",true).put("createdAt",r.clock.instant().toString()).put("firstQualifyingOrderEligible",true).put("evidenceRef","TEST_ONLY_ORDER");}
 ObjectNode finish(){return Json.MAPPER.createObjectNode().put("checkoutId",order.checkout().toString()).put("buyerUserId",buyer.id().toString()).put("walletPaise","30000").put("discountPaise","25000").put("evidenceRef","TEST_ONLY_CAPTURE").put("checkoutCancellationConfirmed",false);}
 JsonNode operation(String source,String type,UUID id,JsonNode body){return r.benefits.apply(source,Json.MAPPER.createObjectNode().put("operationId",id.toString()).put("operationType",type).set("payload",body));}
 @Test void combinedReservationAndReplayHaveOneEffect(){UUID id=UUID.randomUUID();var body=reserve(30000);var result=operation("order","checkout.reserve",id,body);assertEquals("45000",result.path("gatewayPaise").asText());assertEquals(result,operation("order","checkout.reserve",id,body));assertEquals(20000,r.balance(buyer,"available_paise"));assertEquals(30000,r.balance(buyer,"reserved_paise"));assertEquals(1,r.db.count("SELECT count(*) FROM referral_schema.discount_reservation"));}
 @Test void walletFailureRollsBackDiscountAndBudgetDebit(){assertThrows(ReferralProblem.class,()->operation("order","checkout.reserve",UUID.randomUUID(),reserve(60000)));assertEquals(0,r.db.count("SELECT count(*) FROM referral_schema.discount_reservation"));assertEquals(0,r.db.count("SELECT count(*) FROM referral_schema.reservation"));assertEquals(50000,r.balance(buyer,"available_paise"));}
 @Test void excessiveCombinedFundingIsRejectedAtomically(){assertThrows(ReferralProblem.class,()->operation("order","checkout.reserve",UUID.randomUUID(),reserve(80000)));assertEquals(0,r.db.count("SELECT count(*) FROM referral_schema.discount_reservation"));}
 @Test void consumeBothAndRestoreToOriginalSourcesExactlyOnce(){operation("order","checkout.reserve",UUID.randomUUID(),reserve(30000));operation("order","checkout.consume",UUID.randomUUID(),finish());assertEquals(0,r.balance(buyer,"reserved_paise"));var refund=Json.MAPPER.createObjectNode().put("checkoutId",order.checkout().toString()).put("version",1).put("cumulativeWalletPaise","30000").put("cumulativeDiscountPaise","25000").put("evidenceRef","TEST_ONLY_REFUND");UUID id=UUID.randomUUID();operation("finance","checkout.refund",id,refund);operation("finance","checkout.refund",id,refund);assertEquals(50000,r.balance(buyer,"available_paise"));assertEquals("CONSUMED",r.db.one("SELECT status FROM referral_schema.discount_reservation").get("status"));assertEquals(25000,r.db.count("SELECT refunded_paise FROM referral_schema.discount_refund"));}
 @Test void walletRestoreRollsBackWhenDiscountCumulativeIsInvalid(){operation("order","checkout.reserve",UUID.randomUUID(),reserve(30000));operation("order","checkout.consume",UUID.randomUUID(),finish());var refund=Json.MAPPER.createObjectNode().put("checkoutId",order.checkout().toString()).put("version",1).put("cumulativeWalletPaise","30000").put("cumulativeDiscountPaise","25001").put("evidenceRef","TEST_ONLY_REFUND");assertThrows(ReferralProblem.class,()->operation("finance","checkout.refund",UUID.randomUUID(),refund));assertEquals(20000,r.balance(buyer,"available_paise"));}
 @Test void releaseRequiresOwnerCancellationAndCannotFollowConsumption(){operation("order","checkout.reserve",UUID.randomUUID(),reserve(30000));assertThrows(ReferralProblem.class,()->operation("order","checkout.release",UUID.randomUUID(),finish()));operation("order","checkout.consume",UUID.randomUUID(),finish());assertThrows(ReferralProblem.class,()->operation("order","checkout.release",UUID.randomUUID(),finish().put("checkoutCancellationConfirmed",true)));assertEquals(0,r.balance(buyer,"reserved_paise"));}
 @Test void sourcesCannotReserveOrRestoreEachOthersMoney(){assertThrows(ReferralProblem.class,()->operation("finance","checkout.reserve",UUID.randomUUID(),reserve(30000)));assertThrows(ReferralProblem.class,()->operation("order","checkout.refund",UUID.randomUUID(),Json.MAPPER.createObjectNode()));}
 @Test void changedIdempotentRequestCannotChangeTenderAmounts(){UUID id=UUID.randomUUID();operation("order","checkout.reserve",id,reserve(30000));assertThrows(ReferralProblem.class,()->operation("order","checkout.reserve",id,reserve(20000)));assertEquals(30000,r.balance(buyer,"reserved_paise"));}
}
