"use client";

import Image from "next/image";
import type { FormEvent, ReactNode } from "react";
import { ArrowUpRight, Check, Copy, Gift, RefreshCw, ShieldCheck, Users, Wallet } from "lucide-react";
import { referralMessage } from "@/lib/referrals/client";
import { formatPaise, formatReferralTime, type CashoutPage, type ReferralOverview, type RewardPage } from "@/lib/referrals/contracts";
import type { WithdrawalAttempt } from "@/lib/referrals/attempt-store";
import styles from "./referrals.module.css";
export type ReferralMemberViewProps = {
  summary: ReferralOverview | null; rewards: RewardPage; cashouts: CashoutPage;
  loading: boolean; problem: string; notice: string; busy: boolean; fresh: boolean; active: boolean;
  amount: string; confirmed: boolean; attempt: WithdrawalAttempt | null; brand?: ReactNode;
  setAmount: (value: string) => void; setConfirmed: (value: boolean) => void;
  onRefresh: () => void; onShare: (copyOnly: boolean) => void; onWithdraw: (event: FormEvent) => void;
  onCancel: (id: string) => void; onMore: (kind: "rewards" | "cashouts") => void;
};
const status = (value: string) => value.toLowerCase().replaceAll("_", " ");
/** Pure presentation boundary: every displayed balance comes from a validated response. */
export function ReferralMemberView(p: ReferralMemberViewProps) {
  const { summary, rewards, cashouts, loading, problem, notice, busy, fresh, active, amount, confirmed, attempt, brand } = p;
  return <section className={styles.workspace} aria-labelledby="referral-title">
    <header className={styles.hero}><div>{brand}<p className={styles.eyebrow}>CRAVES · REFERRAL REWARDS</p><h1 id="referral-title">Good food. Great connections.</h1><p>Invite people to Craves. Earn from qualifying delivered sales, never from signing someone up.</p></div><div className={styles.heroMark} aria-hidden="true"><Gift size={42} /></div></header>
    <div className={styles.toolbar}><span><ShieldCheck size={16} aria-hidden="true" /> Funded by Craves, not deducted from the selling chef’s earnings</span><button className={styles.secondary} onClick={p.onRefresh} disabled={loading || busy}><RefreshCw size={16} aria-hidden="true" />{loading ? "Refreshing…" : "Refresh"}</button></div>
    {problem && <div role="alert" className={styles.error}>{problem}</div>}{notice && <div role="status" className={styles.notice}>{notice}</div>}
    {loading && !summary && <div className={styles.empty} role="status">Loading your verified referral balances…</div>}
    {!loading && !summary && !problem && <div className={styles.empty}>Your referral account is not available yet.</div>}
    {summary && <>
      {!fresh && !loading && <div className={styles.warning}>These values are not current. Refresh before making a financial request.</div>}
      {summary.onReviewHold && <div className={styles.warning}>Your account is under review. Held rewards cannot be withdrawn or spent. Existing history remains visible.</div>}
      <div className={styles.metrics}>
        <article className={styles.metric}><span><Wallet size={18} aria-hidden="true" />Available rewards</span><strong>{formatPaise(summary.availablePaise)}</strong><small>{BigInt(summary.availablePaise) < BigInt(0) ? "A refund clawback has created a recoverable balance." : "After holds and applicable reviews"}</small></article>
        <article className={styles.metric}><span>Pending rewards</span><strong>{formatPaise(summary.pendingPaise)}</strong><small>{summary.policy ? `${summary.policy.holdDays}-day hold, followed by financial verification` : "Awaiting an active programme policy"}</small></article>
        <article className={styles.metric}><span>Reserved rewards</span><strong>{formatPaise(summary.reservedPaise)}</strong><small>Withdrawals or checkout reservations in progress</small></article>
      </div>
      <p className={styles.asOf}>Balance updated {formatReferralTime(summary.balanceUpdatedAt)} · Retrieved {formatReferralTime(summary.asOf)}</p>
      <div className={styles.columns}>
        <article className={styles.card}><div className={styles.cardHeading}><div><p className={styles.eyebrow}>YOUR INVITATION</p><h2>Share a place at the table.</h2></div><ArrowUpRight size={24} aria-hidden="true" /></div>
          <div className={styles.shareGrid}><div><label className={styles.label} htmlFor="referral-code">Your unique code</label><input id="referral-code" readOnly className={styles.code} value={summary.code.code} /><label className={styles.label} htmlFor="referral-link">Personal referral link</label><input id="referral-link" className={styles.input} readOnly value={summary.code.link} /><div className={styles.actions}><button className={styles.primary} onClick={() => p.onShare(false)}><ArrowUpRight size={16} aria-hidden="true" />Share invitation</button><button className={styles.secondary} onClick={() => p.onShare(true)}><Copy size={16} aria-hidden="true" />Copy link</button></div></div><div className={styles.qr}><Image unoptimized src="/api/referrals/me/code/qr" width={144} height={144} alt="Your personal Craves referral QR code" /><small>Scan to open your invitation</small></div></div>
          <p className={styles.muted}>Attribution is fixed when a new account is created. Sharing does not generate a reward by itself.</p>
        </article>
        <article className={styles.card}><p className={styles.eyebrow}>THREE GENERATIONS</p><h2>A clear, equal earning window.</h2><div className={styles.levels}>{summary.levels.map(level => <div key={level.level}><span className={styles.levelNumber}>{level.level}</span><div><strong>{level.level === 1 ? "Direct invitations" : `Generation ${level.level}`}</strong><small>{summary.policy ? `${summary.policy.ratesBps[level.level - 1] / 100}% of qualifying food subtotal` : "No active rate"}</small></div><b>{formatPaise(level.netEarnedPaise)}</b></div>)}</div><p className={styles.muted}>Only the selling chef’s three ancestors share the percentage reward. Unused shares stay with Craves.</p></article>
      </div>
      <article className={styles.card}><div className={styles.cardHeading}><h2><Users size={20} aria-hidden="true" /> Your referral network</h2><span className={styles.badge}>Privacy protected</span></div><div className={styles.network}>{[1, 2, 3].map(level => <div key={level}><strong>{summary.downline.find(item => item.level === level)?.members ?? "0"}</strong><span>Generation {level}</span></div>)}</div><p className={styles.muted}>These are account counts, not income forecasts. Network details are anonymised.</p></article>
      <div className={styles.columns}>
        <article className={styles.card}><h2>Programme rules</h2>{summary.policy ? <dl className={styles.details}><div><dt>Minimum qualifying food subtotal</dt><dd>{formatPaise(summary.policy.minimumPaise)}</dd></div><div><dt>Seller-chain maximum</dt><dd>{summary.policy.capBps / 100}%</dd></div><div><dt>First qualifying customer-order bonus</dt><dd>{formatPaise(summary.policy.customerBonusPaise)}</dd></div><div><dt>Invitee’s first-order discount</dt><dd>{formatPaise(summary.policy.inviteeDiscountPaise)}</dd></div><div><dt>Active policy revision</dt><dd>{summary.policy.revision}</dd></div></dl> : <p className={styles.warning}>No programme policy is active. Do not promise a rate or reward to invitees.</p>}<p className={styles.muted}>Customer bonuses and discounts use a separate marketing budget, outside the seller-chain cap. Taxes, delivery, tips and post-subtotal discounts are not the reward basis. Refunds can reverse rewards, including those already credited.</p></article>
        <article className={styles.card}><h2>Request a withdrawal</h2><p className={styles.muted}>Minimum {formatPaise(summary.cashout.minimumPaise)}. Eligibility, recipient checks and the approved finance policy are verified again by the server.</p>{!summary.cashout.eligible && <p className={styles.warning}>{referralMessage(summary.cashout.reason)}</p>}
          <form onSubmit={p.onWithdraw}><label className={styles.label} htmlFor="withdrawal-amount">Amount in rupees</label><input id="withdrawal-amount" className={styles.input} inputMode="decimal" placeholder="0.00" value={amount} onChange={event => p.setAmount(event.target.value)} disabled={busy || Boolean(attempt) || !summary.cashout.eligible} required={!attempt} /><label className={styles.check}><input type="checkbox" checked={confirmed} onChange={event => p.setConfirmed(event.target.checked)} disabled={busy || Boolean(attempt)} />I understand this reserves rewards for review; it does not instantly send money.</label>{attempt && <p className={styles.warning}>Pending request: <code>{attempt.id}</code> for {formatPaise(attempt.amountPaise)}. Retry this same reference rather than creating a replacement.</p>}<button className={styles.primary} type="submit" disabled={busy || (!attempt && (!active || !summary.cashout.eligible || !confirmed))}><Check size={16} aria-hidden="true" />{busy ? "Checking…" : attempt ? "Retry the same request" : "Reserve withdrawal"}</button></form>
          <p className={styles.muted}>{summary.spendingEnabled ? "Wallet-spend eligibility is enabled. Checkout must separately validate and reserve the amount." : "Spending rewards at checkout is not currently enabled."}</p>
        </article>
      </div>
      <article className={styles.card}><h2>Reward history</h2>{rewards.items.length === 0 ? <p className={styles.empty}>No rewards yet. Qualifying delivered orders will appear here with their hold date.</p> : <div className={styles.tableWrap}><table className={styles.table}><caption className={styles.srOnly}>Your referral reward history</caption><thead><tr><th>Track</th><th>Created</th><th>Hold ends</th><th>Net reward</th><th>Status</th></tr></thead><tbody>{rewards.items.map(reward => <tr key={reward.id}><td>{reward.track === "UPLINE" ? `Chef · level ${reward.level}` : "Customer bonus"}<small>{reward.id}</small></td><td>{formatReferralTime(reward.createdAt)}</td><td>{formatReferralTime(reward.holdUntil)}</td><td>{formatPaise(reward.netPaise)}{reward.reversedPaise !== "0" && <small>{formatPaise(reward.reversedPaise)} reversed</small>}</td><td><span className={styles.badge}>{status(reward.status)}</span></td></tr>)}</tbody></table></div>}{rewards.nextCursor && <button className={styles.secondary} disabled={busy} onClick={() => p.onMore("rewards")}>Load more rewards</button>}</article>
      <article className={styles.card}><h2>Withdrawal history</h2>{cashouts.items.length === 0 ? <p className={styles.empty}>No withdrawal requests have been made.</p> : <div className={styles.tableWrap}><table className={styles.table}><caption className={styles.srOnly}>Your withdrawal requests</caption><thead><tr><th>Reference</th><th>Requested</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{cashouts.items.map(item => <tr key={item.id}><td><code>{item.id}</code></td><td>{formatReferralTime(item.requestedAt)}</td><td>{formatPaise(item.amountPaise)}</td><td><span className={styles.badge}>{status(item.status)}</span>{item.status === "UNKNOWN" && <small>Do not request a replacement payment.</small>}</td><td>{["RESERVED", "APPROVED"].includes(item.status) ? <button className={styles.secondary} disabled={!active} onClick={() => p.onCancel(item.id)}>Cancel reservation</button> : "—"}</td></tr>)}</tbody></table></div>}{cashouts.nextCursor && <button className={styles.secondary} disabled={busy} onClick={() => p.onMore("cashouts")}>Load more withdrawals</button>}</article>
      <footer className={styles.footer}>Rewards depend on qualifying sales and programme terms. No earnings are guaranteed. A credited wallet balance may be reduced by a later refund.</footer>
    </>}
  </section>;
}
