"use client";

import { useEffect, useState } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { ChevronRight, ClipboardList, Clock, RefreshCw, Utensils } from "lucide-react";
import cravesLogoAsset from "@/assets/images/craves-logo.png";
import type { CustomerOrder } from "@/lib/order-contract";
import { formatOrderStatus } from "@/lib/order-contract";
import { loadSession } from "@/services/auth/cravesAuth";
import { assetUrl } from "@/lib/asset-url";

const cravesLogo = assetUrl(cravesLogoAsset);
function money(amount: number, currency: string) { try { return new Intl.NumberFormat("en-IN", { style: "currency", currency }).format(amount); } catch { return `${currency} ${amount}`; } }
export default function OrdersPage() {
  const navigate = useNavigate(); const [orders, setOrders] = useState<CustomerOrder[]>([]); const [message, setMessage] = useState("Loading your orders…"); const [busy, setBusy] = useState(false);
  async function load() { setBusy(true); try { const response = await fetch("/api/orders", { cache: "no-store" }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.message || "Orders could not be loaded."); setOrders(body); setMessage(body.length ? `${body.length} order${body.length === 1 ? "" : "s"} from Order Service.` : "No orders yet."); } catch (error) { setMessage(error instanceof Error ? error.message : "Orders could not be loaded."); } finally { setBusy(false); } }
  useEffect(() => { void (async () => { if (!await loadSession()) { navigate({ to: "/" }); return; } await load(); })(); }, [navigate]);
  return <div className="min-h-screen bg-cream pb-24"><header className="border-b border-border bg-cream/90"><div className="mx-auto flex max-w-3xl items-center gap-2 px-4 py-4"><Link to="/home" className="flex items-center gap-2"><img src={cravesLogo} alt="Craves" width={36} height={36} className="h-9 w-9" /><span className="font-display text-lg font-bold text-primary">My Orders</span></Link><button type="button" disabled={busy} onClick={() => void load()} className="ml-auto rounded-full border border-border bg-white p-2 text-ink" aria-label="Refresh orders"><RefreshCw className={`h-4 w-4 ${busy ? "animate-spin" : ""}`} /></button></div></header><main className="mx-auto max-w-3xl px-4 pt-6 md:px-6">{!busy && orders.length === 0 ? <div className="rounded-2xl border border-dashed border-border bg-white p-12 text-center"><ClipboardList className="mx-auto h-12 w-12 text-muted-foreground" /><h2 className="mt-4 font-display text-2xl font-bold text-ink">No orders yet</h2><p className="mt-2 text-sm text-muted-foreground">Once a backend checkout creates orders, they will show here.</p><button type="button" onClick={() => navigate({ to: "/home" })} className="btn-primary mt-6">Browse menu</button></div> : <ul className="space-y-3">{orders.map((order) => <li key={order.id}><Link to="/tracking" search={{ id: order.id }} className="flex items-center gap-3 rounded-2xl border border-border bg-card p-4 shadow-sm hover:border-primary"><span className="flex h-16 w-16 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><Utensils className="h-7 w-7" /></span><div className="min-w-0 flex-1"><p className="truncate font-display text-base font-bold text-ink">{order.items[0]?.itemName || order.kitchenName}{order.items.length > 1 ? ` +${order.items.length - 1} more` : ""}</p><p className="mt-0.5 text-xs text-muted-foreground">{order.kitchenName}</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><Clock className="h-3 w-3" />{new Date(order.createdAt).toLocaleString("en-IN")}</p><p className="mt-1 inline-flex rounded-full bg-primary/10 px-2 py-0.5 text-[11px] font-bold text-primary">{formatOrderStatus(order.status)}</p></div><div className="text-right"><p className="font-display text-lg font-bold text-ink">{money(order.grandTotal, order.currency)}</p><ChevronRight className="ml-auto h-4 w-4 text-muted-foreground" /></div></Link></li>)}</ul>}<p role="status" className="mt-4 text-sm text-muted-foreground">{message}</p></main></div>;
}
