import { createHash } from "node:crypto";
import { WEB_LAUNCH_HEADERS } from "./web-launch-security";

const style = `*{box-sizing:border-box}body{margin:0;background:#fff7f0;color:#292321;font:17px/1.6 system-ui,sans-serif;min-height:100svh;display:grid;place-items:center;padding:24px}main{max-width:620px;width:100%;text-align:center;background:#fff;border:1px solid #ffe0cf;border-radius:28px;padding:48px 32px;box-shadow:0 20px 65px #913f1110}img{width:180px;max-width:70%;height:auto}h1{font-size:clamp(30px,6vw,44px);line-height:1.2;letter-spacing:-1.5px;margin:28px 0 16px}p{color:#675d58;margin:14px 0}.eyebrow{font-size:12px;letter-spacing:2px;font-weight:700;text-transform:uppercase;color:#f04424}.status{padding:16px;border-radius:14px;background:#fff5ed}button{font:inherit;font-weight:700;border:0;border-radius:15px;padding:18px 26px;background:#f04424;color:#fff;width:100%;margin-top:20px;cursor:pointer}button:disabled{opacity:.55;cursor:wait}small{display:block;color:#82766e;margin-top:22px}a{color:#d2381d}[hidden]{display:none!important}`;
const waitingScript = `let active=false,opening=false;async function check(){if(active||opening)return;active=true;try{const r=await fetch('/api/web-launch/status',{cache:'no-store',credentials:'omit'});if(r.ok&&(await r.json()).open===true){opening=true;setTimeout(()=>location.reload(),650)}}catch{}finally{active=false}}setInterval(check,1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)check()});check();`;
const controlScript = `const status=document.getElementById('status'),button=document.getElementById('launch'),retry=document.getElementById('retry');let key=new URLSearchParams(location.hash.slice(1)).get('key')||'',busy=false;history.replaceState(null,'',location.pathname);function show(text){status.textContent=text}async function request(method){return fetch('/api/web-launch/control',{method,cache:'no-store',credentials:'omit',headers:{Authorization:'Bearer '+key,...(method==='POST'?{'Content-Type':'application/json'}:{})},...(method==='POST'?{body:JSON.stringify({action:'launch'})}:{})})}async function load(){if(!/^[A-Za-z0-9_-]{43}$/.test(key)){show('Open your private launch link to access this control.');return}try{const r=await request('GET');if(r.status===404){key='';show('This private launch link is invalid or has expired.');return}if(!r.ok)throw Error();const s=await r.json();button.hidden=false;button.disabled=s.phase==='launched';button.textContent=s.phase==='launched'?'Website launched':'Launch Craves web';show(s.phase==='waiting'?'Ready. Visitors are seeing the waiting page.':s.phase==='launched'?'Craves web is live. Visitors have access now.':'Website access is currently open. The waiting page has not been enabled.');retry.hidden=true}catch{show('Unable to verify launch readiness. Retry before launching.');retry.hidden=false}}button.addEventListener('click',async()=>{if(busy)return;busy=true;button.disabled=true;show('Opening the website…');try{const r=await request('POST');if(!r.ok)throw Error();const s=await r.json();if(s.phase!=='launched')throw Error();button.textContent='Website launched';show('Craves web is live. Visitors have access now.');document.getElementById('site').hidden=false}catch{show('Launch has not been confirmed. Retry to verify and safely finish the same launch.');button.disabled=false;retry.hidden=false}finally{busy=false}});retry.addEventListener('click',()=>void load());load();`;

export function launchHtml(control = false): { html: string; headers: Record<string, string> } {
  const script = control ? controlScript : waitingScript;
  const hash = (text: string) => createHash("sha256").update(text).digest("base64");
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${control ? "Craves private web launch" : "Craves — Opening soon"}</title><style>${style}</style></head><body><main><img src="/landing-v20/images/craves-navbar-logo.png" alt="Craves"><p class="eyebrow">${control ? "Private web launch" : "Good food. Good mood."}</p><h1>${control ? "Your launch moment." : "Something delicious is coming."}</h1><p ${control ? 'id="status" class="status"' : 'role="status"'}>${control ? "Checking your private launch link…" : "Craves is getting ready to welcome you. This page will open automatically when we go live."}</p>${control ? '<button id="launch" type="button" hidden>Launch Craves web</button><button id="retry" type="button" hidden>Retry readiness check</button><p id="site" hidden><a href="/" target="_blank" rel="noopener noreferrer">Open Craves</a></p><small>Keep this private link to yourself. This control opens the website only.</small>' : '<small>Thanks for being here.</small>'}</main><script>${script}</script></body></html>`;
  return { html, headers: { ...WEB_LAUNCH_HEADERS, "Content-Type": "text/html; charset=utf-8", "Content-Security-Policy": `default-src 'none'; img-src 'self'; style-src 'sha256-${hash(style)}'; script-src 'sha256-${hash(script)}'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'` } };
}
