package in.craves.integration.referrals.checkout;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class ReferralTenderAllocationTest {
 @Test void exactMultiChefSplitPreservesEveryPaise(){var a=UUID.fromString("00000000-0000-0000-0000-000000000001");var b=UUID.fromString("00000000-0000-0000-0000-000000000002");var result=ReferralTenderAllocation.allocate(List.of(new ReferralTenderAllocation.Child(a,100000,80000),new ReferralTenderAllocation.Child(b,50000,40000)),30000,25000);assertEquals(150000,result.stream().mapToLong(ReferralTenderAllocation.Allocation::grossPaise).sum());assertEquals(30000,result.stream().mapToLong(ReferralTenderAllocation.Allocation::walletPaise).sum());assertEquals(25000,result.stream().mapToLong(ReferralTenderAllocation.Allocation::discountPaise).sum());assertEquals(95000,result.stream().mapToLong(ReferralTenderAllocation.Allocation::gatewayPaise).sum());}
 @Test void randomSplitsStayBoundedAndAreIndependentOfInputOrder(){var random=new Random(1234);for(int n=0;n<1000;n++){var children=new ArrayList<ReferralTenderAllocation.Child>();long gross=0,food=0;for(int i=0;i<1+random.nextInt(15);i++){long f=random.nextInt(100000)+1,g=f+random.nextInt(30000);food+=f;gross+=g;children.add(new ReferralTenderAllocation.Child(new UUID(0,i+1),g,f));}long discount=random.nextLong(food+1),wallet=random.nextLong(gross-discount+1);var a=ReferralTenderAllocation.allocate(children,wallet,discount);Collections.reverse(children);assertEquals(a,ReferralTenderAllocation.allocate(children,wallet,discount));assertEquals(wallet,a.stream().mapToLong(ReferralTenderAllocation.Allocation::walletPaise).sum());assertEquals(discount,a.stream().mapToLong(ReferralTenderAllocation.Allocation::discountPaise).sum());for(var c:a){assertTrue(c.gatewayPaise()>=0);assertEquals(c.grossPaise(),c.gatewayPaise()+c.walletPaise()+c.discountPaise());}}}
 @Test void fullyWalletFundedCheckoutHasNoExternalPayment(){var r=ReferralTenderAllocation.allocate(List.of(new ReferralTenderAllocation.Child(UUID.randomUUID(),10000,8000)),7500,2500);assertEquals(0,r.getFirst().gatewayPaise());}
 @Test void excessiveDiscountDuplicateChildAndNegativeAmountsFail(){UUID id=UUID.randomUUID();var c=new ReferralTenderAllocation.Child(id,100,80);assertThrows(IllegalArgumentException.class,()->ReferralTenderAllocation.allocate(List.of(c),0,81));assertThrows(IllegalArgumentException.class,()->ReferralTenderAllocation.allocate(List.of(c,c),0,1));assertThrows(IllegalArgumentException.class,()->ReferralTenderAllocation.allocate(List.of(c),-1,0));assertThrows(IllegalArgumentException.class,()->ReferralTenderAllocation.allocate(List.of(c),101,0));}
}
