package in.craves.integration.referrals.checkout;
import in.craves.integration.ledger.LedgerPostingService;
import in.craves.integration.referrals.transport.ReferralSourceClient;
import in.craves.integration.refund.*;
import in.craves.integration.refund.RefundModels.*;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
@EnabledIfEnvironmentVariable(named="LEDGER_TEST_JDBC_URL",matches=".+")
class ReferralSplitRefundDatabaseTest extends ReferralCheckoutFundingDatabaseTest {
 ReferralRefundService refunds;RefundRequestService source;ReferralSourceClient referral;
 @BeforeEach void refundSetup()throws Exception{referral=mock(ReferralSourceClient.class);refunds=new ReferralRefundService(r.db,json,referral,new LedgerPostingService(r.db,json,true),r.manager);source=new RefundRequestService(r.db,new RefundEventValidator());source.setReferralRefunds(refunds);reply();}
 void reply()throws Exception{doAnswer(i->{var p=json.readTree((byte[])i.getArgument(1)).path("payload");return new ReferralSourceClient.Reply(200,json.writeValueAsBytes(json.createObjectNode().put("checkoutId",p.path("checkoutId").asText()).put("version",p.path("version").intValue()).put("walletRefundedPaise",p.path("cumulativeWalletPaise").asText()).put("discountRefundedPaise",p.path("cumulativeDiscountPaise").asText())));}).when(referral).send(any(),any());}
 void funded(){var value=create();if(value.amount().signum()>0)paid(value.paymentOrderId());assertTrue(service.runOne());}
 EventEnvelope<RefundRequestedData> event(BigDecimal amount){return new EventEnvelope<>(UUID.randomUUID(),"REFUND_REQUESTED","1.0",Instant.now(),checkout,UUID.randomUUID(),"order-service",order.toString(),new RefundRequestedData(checkout,order,buyer,amount,"INR","CHEF_DECLINED",Instant.now()));}
 boolean accept(EventEnvelope<RefundRequestedData> e)throws Exception{String raw=json.writeValueAsString(e);return r.tx.execute(s->source.accept(e,raw));}
 void providerRefunded(){r.db.execute("UPDATE payment_schema.refund SET status='SUCCESS',provider_status='processed',provider_refund_id='rfnd_TestOnly'");}
 @Test void providerRefundUsesOnlyItsOriginalTenderAllocation()throws Exception{funded();var e=event(new BigDecimal("1000.00"));assertTrue(accept(e));assertFalse(accept(e));assertEquals(new BigDecimal("450.00"),r.db.queryForObject("SELECT amount FROM payment_schema.refund",BigDecimal.class));assertFalse(refunds.runOne());verifyNoInteractions(referral);assertEquals(0,r.count("refund_status_outbox"));}
 @Test void fullSplitRefundRestoresWalletAndBudgetBeforePublishingGrossSuccess()throws Exception{funded();accept(event(new BigDecimal("1000.00")));providerRefunded();assertTrue(refunds.runOne());assertFalse(refunds.runOne());assertEquals("COMPLETE",r.db.queryForObject("SELECT state FROM payment_schema.referral_refund_allocation",String.class));assertEquals("1000.00",r.db.queryForObject("SELECT payload->'data'->>'refundAmount' FROM payment_schema.refund_status_outbox",String.class));assertEquals(30000,r.db.queryForObject("SELECT wallet_refunded_paise FROM payment_schema.referral_refund_sequence",Integer.class));assertEquals(25000,r.db.queryForObject("SELECT discount_refunded_paise FROM payment_schema.referral_refund_sequence",Integer.class));assertEquals(2,r.count("ledger_transaction"));assertEquals(0,new BigDecimal(r.db.queryForObject("SELECT (sum(debit_amount)-sum(credit_amount))::text FROM payment_schema.ledger_line",String.class)).signum());}
 @Test void walletRefundTimeoutRetainsOriginalOperationAndDefersCustomerSuccess()throws Exception{funded();accept(event(new BigDecimal("1000.00")));providerRefunded();doThrow(new java.io.IOException("test timeout")).when(referral).send(any(),any());assertTrue(refunds.runOne());String original=r.db.queryForObject("SELECT operation_envelope::text FROM payment_schema.referral_refund_allocation",String.class);assertEquals(0,r.count("refund_status_outbox"));assertEquals(1,r.count("ledger_transaction"));reply();r.db.execute("UPDATE payment_schema.referral_refund_allocation SET next_attempt_at=now()");assertTrue(refunds.runOne());assertEquals(original,r.db.queryForObject("SELECT operation_envelope::text FROM payment_schema.referral_refund_allocation",String.class));assertEquals(1,r.count("refund_status_outbox"));}
 @Test void zeroExternalRefundNeverCreatesAProviderRefundIdentity()throws Exception{funding.put("walletPaise","75000").put("gatewayPaise","0");funded();accept(event(new BigDecimal("1000.00")));assertEquals("BENEFITS_PENDING",r.db.queryForObject("SELECT status FROM payment_schema.refund",String.class));assertTrue(refunds.runOne());assertEquals("SUCCESS",r.db.queryForObject("SELECT status FROM payment_schema.refund",String.class));assertNull(r.db.queryForObject("SELECT provider_refund_id FROM payment_schema.refund",String.class));assertEquals(0,r.db.queryForObject("SELECT count(*) FROM payment_schema.ledger_line WHERE account_code='GATEWAY_CLEARING'",Integer.class));}
 @Test void unsupportedPartialAllocationRollsBackInboxAndMoney()throws Exception{funded();assertThrows(Exception.class,()->accept(event(new BigDecimal("999.99"))));assertEquals(0,r.count("refund_request_inbox"));assertEquals(0,r.count("refund"));assertEquals(0,r.count("referral_refund_allocation"));}
 @Test void originalProviderSuccessEventIsDeferredAndPendingUsesGrossAmount()throws Exception{funded();accept(event(new BigDecimal("1000.00")));var payload=json.createObjectNode();payload.putObject("data").put("status","SUCCESS").put("refundAmount","450.00");var original=new RefundStatusEventFactory.SerializedRefundStatusEvent(UUID.randomUUID(),"REFUND_STATUS_CHANGED","1.0",Instant.now(),checkout,UUID.randomUUID(),order,payload.toString(),"TEST_ONLY_EVENT");assertNull(refunds.customerEvent(original));((com.fasterxml.jackson.databind.node.ObjectNode)payload.path("data")).put("status","PENDING");var pending=new RefundStatusEventFactory.SerializedRefundStatusEvent(original.eventId(),original.eventType(),original.eventVersion(),original.occurredAt(),checkout,original.causationId(),order,payload.toString(),original.eventKey());assertEquals(new BigDecimal("1000.00"),json.readTree(refunds.customerEvent(pending).payloadJson()).path("data").path("refundAmount").decimalValue());}
 @Test void completeRefundEvidenceCannotBeRewritten()throws Exception{funded();accept(event(new BigDecimal("1000.00")));providerRefunded();refunds.runOne();assertThrows(Exception.class,()->r.db.execute("UPDATE payment_schema.referral_refund_allocation SET gateway_paise=1"));assertThrows(Exception.class,()->r.db.execute("DELETE FROM payment_schema.referral_refund_allocation"));}
}
