import { useEffect, useState } from "react";
import { X } from "lucide-react";
import type { CustomerProfile } from "@/lib/profile-contract";
export function EditProfileModal({ open, profile, onClose, onSaved }: { open: boolean; profile: CustomerProfile | null; onClose: () => void; onSaved: (profile: CustomerProfile) => void }) {
  const [firstName, setFirstName] = useState(""); const [lastName, setLastName] = useState(""); const [email, setEmail] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (open) { setFirstName(profile?.firstName ?? ""); setLastName(profile?.lastName ?? ""); setEmail(profile?.email ?? ""); setError(""); } }, [open, profile]);
  if (!open) return null;
  async function save() { setBusy(true); setError(""); try { const response = await fetch("/api/customer/profile", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ firstName, lastName, email: email.trim() || null }) }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.message || "Profile could not be saved."); onSaved(body); onClose(); } catch (error) { setError(error instanceof Error ? error.message : "Profile could not be saved."); } finally { setBusy(false); } }
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/50 md:items-center"><div className="w-full max-w-md rounded-t-3xl bg-cream p-6 md:rounded-3xl"><div className="flex items-center justify-between"><h2 className="font-display text-xl font-bold text-ink">Edit profile</h2><button type="button" onClick={onClose} className="rounded-full p-2"><X className="h-5 w-5" /></button></div><div className="mt-5 space-y-4"><label className="block text-xs font-semibold text-ink">First name<input value={firstName} maxLength={100} onChange={(e) => setFirstName(e.target.value)} className="mt-1 w-full rounded-xl border border-border bg-white p-3 text-sm" /></label><label className="block text-xs font-semibold text-ink">Last name<input value={lastName} maxLength={100} onChange={(e) => setLastName(e.target.value)} className="mt-1 w-full rounded-xl border border-border bg-white p-3 text-sm" /></label><label className="block text-xs font-semibold text-ink">Email (optional)<input type="email" value={email} maxLength={320} onChange={(e) => setEmail(e.target.value)} className="mt-1 w-full rounded-xl border border-border bg-white p-3 text-sm" /></label>{profile && <p className="rounded-xl bg-secondary p-3 text-sm text-muted-foreground">Phone number: {profile.registeredPhoneNumber} (verified sign-in identity)</p>}</div>{error && <p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}<button type="button" disabled={busy} onClick={() => void save()} className="btn-primary mt-6 w-full justify-center disabled:opacity-50">{busy ? "Saving…" : "Save changes"}</button></div></div>;
}
export default EditProfileModal;
